- name: Setup K8S MultiMaster Cluster
  hosts: "k8s_masters, k8s_workers, k8s_utils"
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter sudo password"
      private: yes

  roles:
    - k8s_setup
