- name: Add conf for containerd
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

- name: Enable some module
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Install Containerd.io package
  ansible.builtin.apt:
    name: containerd.io
    state: present

- name: Configure containerd
  ansible.builtin.shell: |
    mkdir -p /etc/containerd
    containerd config default | tee /etc/containerd/config.toml
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml

- name: Set sysctl parameters and reload
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-containerd.conf
  loop:
    - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }

- name: enable and start containerd
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: restarted

- name: Exclude kube components from apt upgrades
  ansible.builtin.shell: |
    apt-mark hold containerd
